### ISSUE TITLE
Atom and Intentions version issue Installing/Uninstalling - Ubuntu 18.04

### ISSUE THREAD

**Issue by savicheema** [steelbrain/intentions#102]
Lately I have been getting this error on startup  Atom editor. (_This issue maybe related to Ubuntu/Linux only_)
 
![screenshot_6](https://user-images.githubusercontent.com/1475453/123510972-30fc1080-d69c-11eb-881e-dd4cfed1a558.png)
Linked Issue is closed: #64 

When I try to uninstall/re-install the intentions package, I see this message in packages section of my editor.
It says: **version 2.1.0  is not the latest version available for this package, but it’s the latest that is compatible with your version of Atom.**
![screenshot_7](https://user-images.githubusercontent.com/1475453/123511026-8801e580-d69c-11eb-83c2-b871b8621692.png)

But there is no improvement, even after that step.

I have installed latest versions of Atom editor through Ubuntu Software store and also through cloning Github repository: [Hacking on Atom Core](https://flight-manual.atom.io/hacking-atom/sections/hacking-on-atom-core/#platform-linux).
The problem is because I am unable to uninstall my current Atom editor, I am not able to access my new installations.
![screenshot_9](https://user-images.githubusercontent.com/1475453/123511107-18402a80-d69d-11eb-88b3-8b2c78e93237.png)

Atom    : 1.48.0
Electron: 5.0.13
Chrome  : 73.0.3683.121
Node    : 12.0.0
Ubuntu : 18.04

**Comment by aminya** [comment]
This package does not work on older Atoms. You should install the latest version of Atom from: https://atom.io/

If you are having an issue with installing new Atom versions open an issue in the Atom repository
