### ISSUE TITLE
Use Atom command listener

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/intentions#23]
It seems that currently the command to open the intentions list (<Kbd>Alt</kbd>+<kbd>Enter</kbd> on Windows) is implemented using a custom DOM event listener (due to an old Atom bug?).

Move back to the Atom command API so the command is shown in the settings.

**Comment by steelbrain** [comment]
Thanks

**Comment by steelbrain** [comment]
Done in v1.1.0
