### ISSUE TITLE
Replace vanilla-jsx with solid

### ISSUE THREAD

**Issue by Arcanemagus** [steelbrain/intentions#27]
When installing dependencies a warning is thrown saying that `vanilla-jsx` is deprecated in favor of `preact`.

**Comment by steelbrain** [comment]
Thanks for reminding me

**Comment by steelbrain** [comment]
Well this is hard because we can easily port the functions and stuff onto a react component but react components are supposed to be isolated so when we render them, we have no way of calling their props, so we're gonna stick with vanilla-jsx while it's working
