### ISSUE TITLE
It seems like intentions broke with linter 2.0

### ISSUE THREAD

**Issue by beliasson** [steelbrain/intentions#47]
Since the new linter version yesterday intentions no longer shows me the intentions list, when pressing the shortcut.

I am using intentions together with linter-spell to get spell correction support.

Does anybody get the same bug?

**Comment by Arcanemagus** [comment]
![image](https://cloud.githubusercontent.com/assets/427137/23960042/0a91509a-0964-11e7-990a-2ca268758ea7.png)

It's working for `linter-eslint` at least, can you check the keybinding resolver (<kbd>Ctrl</kbd>+<kbd>.</kbd>) to make sure the keys are triggering it?

**Comment by beliasson** [comment]
![screen shot 2017-03-15 at 17 58 46](https://cloud.githubusercontent.com/assets/821724/23960791/32777158-09a9-11e7-9302-6a971e34eb69.png)

seems to be triggering. Do I maybe have to blame linter-spell for the bug? :)

**Comment by Arcanemagus** [comment]
Probably 😛, looking over their code...

**Comment by Arcanemagus** [comment]
Actually, it looks like `linter-spell` isn't using the `fix` attribute of Linter to implement this, they are consuming the intentions service on their own and implementing it there, so this is definitely a bug specifically with how their usage of `intentions` is interacting with it, possibly here though. It will have to wait till @steelbrain can take a look though as I'm not as familiar with this.

**Comment by steelbrain** [comment]
Will investigate

**Comment by steelbrain** [comment]
Found out the bug, `linter-spell` is using the highly unrecommended, internal, linter-self service which has been removed in linter v2. Fixing linter-spell in a PR soon

**Comment by steelbrain** [comment]
Opened https://github.com/yitzchak/linter-spell/pull/45

**Comment by beliasson** [comment]
Wow, that is so great! Thank you **very much** for fixing it!
