### ISSUE TITLE
intentions:show triggers error

### ISSUE THREAD

**Issue by pablooliveira** [steelbrain/intentions#68]
Hi,

I have this error both with atom 1.18.0 and 1.19.0-beta5 on linux.
I'm using linter-spell on a simple test .txt file.

When using `alt+enter` to run `intentions:show`, nothing happens and I get the following stack trace on the developers tools console:

```
main.js [sm]:34 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined(…)

(anonymous function) @ main.js [sm]:34
step main.js:9(anonymous function) @ main.js:9
(anonymous function) @ main.js:9
(anonymous function) @ commands.js 
[sm]:219emit @ emitter.js:84
(anonymous function) @ commands.js [sm]:209
step @ commands.js:9
(anonymous function) @ commands.js:9
(anonymous function) @ commands.js:9
(anonymous function) @ commands.js [sm]:127
step @ commands.js:9
(anonymous function) @ commands.js:9
(anonymous function) @ commands.js:9
intentionsShow @ commands.js [sm]:40
module.exports.CommandRegistry.handleCommandEvent @ <embedded>:18901
(anonymous function) @ <embedded>:18639
module.exports.KeymapManager.dispatchCommandEvent @ <embedded>:66514
module.exports.KeymapManager.handleKeyboardEvent @ <embedded>:66305
module.exports.WindowEventHandler.handleDocumentKeyEvent @ <embedded>:15166
(anonymous function) @ <embedded>:15069
```

I attach a screenshot demonstrating the issue.

![screenshot from 2017-07-26 19-57-19](https://user-images.githubusercontent.com/499257/28635999-020f603c-723d-11e7-8c45-8b17e9fc9b47.png)

What is going on ?

Thanks !

**Comment by steelbrain** [comment]
Hi @pablooliveira 

Can you restart Atom and see if the problem persists?

**Comment by pablooliveira** [comment]
Unfortunately, the problem persists after a restart.

**Comment by pablooliveira** [comment]
I confirm ca3b1dc fixes my bug ! Thanks a bunch :tada:

**Comment by steelbrain** [comment]
Thanks for promptly reporting the bug! 🎉
